name: ebase5 Build Client Prod Artifact

on:
  push:
    branches:
      - production

jobs:
  build-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          npm clean-install --production=false
          npm run build
        working-directory: ./
        env:
          CI: true
          NODE_ENV: production
      - name: create zip-archive
        uses: vimtor/action-zip@v1
        with:
          files: ./dist/ ./client/web.config
          dest: spok-client.zip
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spok-client.zip
          path: spok-client.zip
